"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { donationMenu, type DonationEvent } from "@/lib/donation-game";

type Status = { donationUrl: string; canConnect: boolean; connected: boolean; error?: string; recent: DonationEvent[] };
export default function DonationsPage() {
  const [status, setStatus] = useState<Status | null>(null);
  const [amount, setAmount] = useState("150"); const [message, setMessage] = useState(""); const [name, setName] = useState("Тестовый свидетель"); const [notice, setNotice] = useState("");
  const load = async () => { const response = await fetch("/api/donation-alerts/status", { cache: "no-store" }); setStatus(await response.json()); };
  useEffect(() => { load(); const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer); }, []);
  const test = async () => { const response = await fetch("/api/donation-alerts/test", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amount, username: name, message }) }); const data = await response.json(); setNotice(data.error || `Тест отправлен: ${data.event.action.title}`); load(); };
  return <main className="donations-page"><header><Link href="/">← К ИГРЕ</Link><a href={status?.donationUrl || "https://www.donationalerts.com/r/vivi_frox"} target="_blank">ОТКРЫТЬ DONATION ALERTS ↗</a></header><section className="donation-hero"><p>ДОНАТНЫЙ СТОЛ · СВАДЬБА ВИВИ × ХИНОЧКИ</p><h1>Дарим не «выпей»,<br/>а <i>повод для свадебной катастрофы.</i></h1><div className={status?.connected ? "connection live" : "connection"}>{status?.connected ? "● DonationAlerts подключён" : "○ DonationAlerts пока не подключён"}</div>{!status?.connected && <div className="connect-box"><p>Добавь параметры из <code>.env.example</code> в новый файл <code>.env.local</code>, затем перезапусти игру.</p>{status?.canConnect ? <a className="connect" href="/api/donation-alerts/connect">ПОДКЛЮЧИТЬ DONATIONALERTS</a> : <p className="warning">Для безопасного подключения нужны Client ID и Client Secret зарегистрированного приложения. Их нельзя вставлять в чат или в код.</p>}</div>}{status?.error && <p className="warning">{status.error}</p>}</section><section className="donation-menu"><h2>Свадебная касса</h2><p>Сумма открывает событие; сообщение донатера — его тема. Алко‑тост всегда опционален: можно выбрать воду, сок, чай или вообще просто поднять бокал в камеру.</p><div>{donationMenu.map(({ amount, action }) => <article key={amount}><b>{amount} ₽</b><h3>{action.title}</h3><p>{action.description}</p>{action.toast && <small>Тост: «{action.toast}»</small>}</article>)}</div></section><section className="test-panel"><div><p>ПРОВЕРКА ПЕРЕД СТРИМОМ</p><h2>Тестовый донат</h2><small>Он не создаёт реальный платёж — только проверяет очередь и эффект на экране ведущей.</small></div><label>Сумма ₽<input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="numeric"/></label><label>Имя<input value={name} onChange={(e) => setName(e.target.value)}/></label><label className="message">Сообщение<textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Например: Виви и Хиночка, за ваш семейный DLC!"/></label><button onClick={test}>ЗАПУСТИТЬ ТЕСТ</button>{notice && <strong>{notice}</strong>}</section><section className="donation-log"><p>ПОСЛЕДНИЕ ПОСТУПЛЕНИЯ</p>{status?.recent?.length ? status.recent.map((event) => <article key={event.id}><b>{event.username}</b><span>{event.amount} {event.currency}</span><strong>{event.action.title}</strong>{event.message && <q>{event.message}</q>}</article>) : <div className="empty">Пока пусто. Нажми «Тестовый донат» — он появится здесь и в игре.</div>}</section></main>;
}
