"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { bingoEvents, compatibilityPairs, courtCases, flags, getRandom, knowledgeQuestions, questions, rouletteSectors, thisIsUs, tierCards, wouldYouRather } from "@/lib/game-data";
import type { DonationEvent } from "@/lib/donation-game";

type Metric = "chemistry" | "compatibility" | "knowledge" | "trust" | "chaos" | "flags";
type Mode = "home" | "questions" | "bingo" | "this" | "compatibility" | "tier" | "court" | "contract" | "flags" | "knowledge" | "would" | "dowry" | "life" | "roulette" | "final";
const metricLabels: Record<Metric, string> = { chemistry: "Химия", compatibility: "Совместимость", knowledge: "Знание", trust: "Доверие", chaos: "Хаос", flags: "Red Flags" };
const modeList: { id: Mode; icon: string; label: string }[] = [
  {id:"questions",icon:"?",label:"123 вопроса"},{id:"bingo",icon:"▦",label:"Бинго чата"},{id:"this",icon:"↔",label:"Кто из нас"},{id:"compatibility",icon:"♥",label:"Совпадём?"},{id:"tier",icon:"≋",label:"Тир-лист"},{id:"court",icon:"⚖",label:"Семейный суд"},{id:"contract",icon:"✎",label:"Договор"},{id:"flags",icon:"⚑",label:"Флаги"},{id:"knowledge",icon:"◎",label:"Знаешь меня?"},{id:"would",icon:"↯",label:"Что выберешь"},{id:"dowry",icon:"₽",label:"Приданое"},{id:"life",icon:"⌂",label:"Совместная жизнь"},{id:"roulette",icon:"◌",label:"Рулетка"},{id:"final",icon:"★",label:"Экзамен"},
];
const levels = ["💍 В БРАЧНЫЙ ДОГОВОР", "💕 ОДОБРЕНО", "🤔 ОБСУДИМ", "🚩 RED FLAG", "⚖️ СЕМЕЙНЫЙ СУД", "💔 ПРИЧИНА ДЛЯ РАЗВОДА"];

function marriageStatus(m: Record<Metric, number>) { const s=m.chemistry+m.compatibility+m.knowledge+m.trust-m.flags+Math.min(m.chaos,15)/3; return m.flags>22?"Красные флаги образовали букет":s>55?"Подозрительно стабильно":s>30?"Допущены до свадьбы под наблюдением чатерсов":s>12?"Экспериментальный союз":"Чат рекомендует адвоката"; }
function Button({children,onClick,kind="secondary",disabled=false}:{children:React.ReactNode;onClick?:()=>void;kind?:"primary"|"secondary";disabled?:boolean}) { return <button className={kind} onClick={onClick} disabled={disabled}>{children}</button>; }

export default function HostPage() {
  const [mode,setMode]=useState<Mode>("home"), [names,setNames]=useState(["Виви","Хиночка"]), [metrics,setMetrics]=useState<Record<Metric,number>>({chemistry:18,compatibility:15,knowledge:12,trust:11,chaos:8,flags:3});
  const [history,setHistory]=useState(["Стрим готов. Чат допущен к принятию решений."]), [used,setUsed]=useState<number[]>([]), [question,setQuestion]=useState(questions[0]);
  const [prompt,setPrompt]=useState(getRandom(thisIsUs)), [options,setOptions]=useState<string[]>(["Виви","Хиночка","Оба","Никто"]), [title,setTitle]=useState("КТО ИЗ НАС?"), [roundId,setRoundId]=useState(0);
  const [answers,setAnswers]=useState(["",""]), [revealed,setRevealed]=useState(false), [answerStatus,setAnswerStatus]=useState<Record<string,boolean>>({}), [bingo,setBingo]=useState(bingoEvents.slice(0,25).map((text,i)=>({text,checked:i===12})));
  const [court,setCourt]=useState(getRandom(courtCases)), [seconds,setSeconds]=useState(60), [timer,setTimer]=useState(false), [contract,setContract]=useState<string[]>([]), [draft,setDraft]=useState(""), [tier,setTier]=useState<Record<string,string>>({}), [room]=useState("VIVI-HINA"), [roulette,setRoulette]=useState("КРУТИМ?"), [votes,setVotes]=useState<{id:string;vote:string;at:number}[]>([]), [lastDonation,setLastDonation]=useState<DonationEvent|null>(null), [shareBase,setShareBase]=useState(""), [viviKey,setViviKey]=useState(""), [hinaKey,setHinaKey]=useState("");
  const status=useMemo(()=>marriageStatus(metrics),[metrics]); const chatOptions=useMemo(()=>["this","compatibility","flags","would"].includes(mode)?options:mode==="court"?[`${names[0]} права`,`${names[1]} прав`,`Виноваты оба`,`РАЗВОД`]:[],[mode,options,names]); const voteTally=useMemo(()=>Object.fromEntries(chatOptions.map(option=>[option,votes.filter(v=>v.vote===option).length])),[chatOptions,votes]); const shareRoot=shareBase.trim().replace(/\/$/,""); const playerHref=(player:"vivi"|"hina",key:string)=>`${shareRoot}/player?room=${room}&player=${player}${key?`&key=${encodeURIComponent(key)}`:""}`; const audienceHref=`${shareRoot}/audience?room=${room}`; const log=(x:string)=>setHistory(h=>[x,...h].slice(0,8));
  const change=(key:Metric,n:number)=>{setMetrics(m=>({...m,[key]:Math.max(0,Math.min(99,m[key]+n))}));log(`${metricLabels[key]} ${n>0?"+":""}${n}`)};
  const chooseQuestion=(n?:number)=>{const avail=questions.filter(q=>!used.includes(q.id));const q=n?questions.find(x=>x.id===n):getRandom(avail.length?avail:questions);if(q){setQuestion(q);setUsed(u=>[...new Set([...u,q.id])]);setRevealed(false);log(`Вопрос №${q.id}: ${q.category}`)}};
  const startChoice=(kind:"this"|"compatibility"|"flags"|"would")=>{setAnswers(["",""]);setRevealed(false);setAnswerStatus({});setRoundId(Date.now());void fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({room,resetAnswers:true})});if(kind==="this"){setTitle("КТО ИЗ НАС?");setPrompt(getRandom(thisIsUs));setOptions([names[0],names[1],"Оба","Никто"])} if(kind==="compatibility"){setTitle("СОВПАДЁМ ИЛИ РАЗВЕДЁМСЯ");setOptions(getRandom(compatibilityPairs));setPrompt("Выберите вариант скрытно — потом узнаем, насколько всё плохо.")} if(kind==="flags"){setTitle("RED FLAG / GREEN FLAG");setPrompt(getRandom(flags));setOptions(["🟢 Green Flag","🟡 Спорно","🔴 Red Flag","⚫ Бежать"])} if(kind==="would"){setTitle("ЧТО БЫ ТЫ ВЫБРАЛ?");setPrompt("Ни один вариант нельзя пропускать без драматического комментария.");setOptions(getRandom(wouldYouRather))}};
  const showMode=(m:Mode)=>{setMode(m); if(["this","compatibility","flags","would"].includes(m))startChoice(m as "this");};
  const reveal=async()=>{const r=await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({room,revealAnswers:true})});const data=await r.json();const next=[data.privateAnswers?.vivi?.value||"",data.privateAnswers?.hina?.value||""];setAnswers(next);setRevealed(true);if(next[0]&&next[1]){if(next[0]===next[1]){change(title.includes("СОВПАД")?"compatibility":"knowledge",3);log("СОВПАЛИ — чат в восторге!")}else{change("chaos",2);log("НЕ СОВПАЛИ — нужен комментарий.")}}};
  const hasBingo=[0,1,2,3,4].some(r=>bingo.slice(r*5,r*5+5).every(x=>x.checked))||[0,1,2,3,4].some(c=>[0,1,2,3,4].every(r=>bingo[r*5+c].checked));
  const sync=async()=>{try{const r=await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({room,state:{mode,names,metrics,status,title,roundId,question,prompt,options,chatOptions,answers,revealed,bingo,court,contract,tier,roulette,donation:lastDonation,updatedAt:Date.now()}})});const data=await r.json();setVotes(data.votes||[]);setAnswerStatus(data.answerStatus||{})}catch{}};
  useEffect(()=>{sync();const i=window.setInterval(sync,3000);return()=>clearInterval(i)},[mode,names,metrics,status,title,roundId,question,prompt,options,chatOptions,answers,revealed,bingo,court,contract,tier,roulette]);
  useEffect(()=>{if(!timer||seconds<1)return;const id=setTimeout(()=>setSeconds(s=>s-1),1000);return()=>clearTimeout(id)},[timer,seconds]);
  useEffect(()=>{const poll=async()=>{try{const r=await fetch("/api/donation-alerts/sync",{cache:"no-store"});const data=await r.json();(data.events||[]).forEach((event:DonationEvent)=>{setLastDonation(event);setHistory(h=>[`ДОНАТ ${event.amount} ₽ · ${event.username}: ${event.action.title}`,...h].slice(0,8));if(event.action.metric&&event.action.metricChange)setMetrics(m=>({...m,[event.action.metric!]:Math.max(0,Math.min(99,m[event.action.metric!]+event.action.metricChange!))}));if(event.action.mode)setMode(event.action.mode as Mode);if(event.action.mode==="compatibility")startChoice("compatibility");if(event.action.id==="case"&&event.message.trim())setCourt(event.message.trim());if(event.action.id==="amendment"&&event.message.trim())setDraft(event.message.trim());if(event.action.toast)setRoulette(event.action.toast)});}catch{}};poll();const i=window.setInterval(poll,5000);return()=>clearInterval(i)},[]);
  return <main className="app-shell"><header className="masthead"><div className="brand"><span>✦</span><div><b>ТЕСТ НА СОУЛМЕЙТА</b><small>ПРЕДСВАДЕБНЫЕ ИСПЫТАНИЯ</small></div></div><div className="top-actions"><Link href="/donations" target="_blank">₽ ДОНАТЫ</Link><Link href={`/screen?room=${room}`} target="_blank">◉ ЭКРАН ДЛЯ OBS</Link><Link className="lime" href={`/audience?room=${room}`} target="_blank">ЧАТ: {room}</Link></div></header>
    <nav className="side-nav"><button className={mode==="home"?"selected":""} onClick={()=>showMode("home")}><b>⌂</b>Главный стол</button>{modeList.map(x=><button key={x.id} className={mode===x.id?"selected":""} onClick={()=>showMode(x.id)}><b>{x.icon}</b>{x.label}</button>)}</nav>
    <section className="workspace"><section className="scoreboard"><div className="players"><input value={names[0]} onChange={e=>setNames([e.target.value,names[1]])}/><span>×</span><input value={names[1]} onChange={e=>setNames([names[0],e.target.value])}/></div><div className="status-stamp">СТАБИЛЬНОСТЬ БРАКА <strong>{status}</strong></div><div className="metric-row">{(Object.keys(metricLabels) as Metric[]).map(k=><div className="metric" key={k}><span>{metricLabels[k]}</span><b>{metrics[k]}</b><div><button onClick={()=>change(k,-1)}>−</button><button onClick={()=>change(k,1)}>+</button><button onClick={()=>change(k,5)}>+5</button></div></div>)}</div></section>
      {mode==="home"&&<Home status={status} history={history} go={showMode} random={()=>showMode(getRandom(modeList).id)}/>} 
      {mode==="questions"&&<Question question={question} used={used.length} next={chooseQuestion} answered={()=>{change("knowledge",1);chooseQuestion()}}/>}
      {["this","compatibility","flags","would"].includes(mode)&&<Choice title={title} names={names} answers={answers} answerStatus={answerStatus} revealed={revealed} reveal={reveal} next={()=>startChoice(mode as "this")}/>} 
      {mode==="bingo"&&<Bingo bingo={bingo} setBingo={setBingo} has={hasBingo}/>} 
      {mode==="tier"&&<Tier tier={tier} setTier={setTier}/>} 
      {mode==="court"&&<Court court={court} names={names} seconds={seconds} timer={timer} toggle={()=>setTimer(!timer)} reset={()=>{setSeconds(60);setTimer(false)}} next={()=>{setCourt(getRandom(courtCases));setSeconds(60)}} vote={x=>{change(x==="РАЗВОД"?"flags":"chaos",x==="РАЗВОД"?5:2);setCourt(getRandom(courtCases))}}/>}
      {mode==="contract"&&<Contract draft={draft} setDraft={setDraft} contract={contract} setContract={setContract}/>} 
      {mode==="knowledge"&&<Knowledge names={names} question={getRandom(knowledgeQuestions)} change={change}/>} 
      {mode==="dowry"&&<Dowry change={change}/>} {mode==="life"&&<Life add={x=>{setContract(c=>[...c,`Альт-жизнь: ${x}`]);log(`Чат выбрал: ${x}`)}}/>}
      {mode==="roulette"&&<Roulette value={roulette} spin={()=>{const x=getRandom(rouletteSectors);setRoulette(x);log(`Рулетка: ${x}`)}}/>} {mode==="final"&&<Final names={names} status={status} metrics={metrics}/>} 
    </section>
    <aside className="right-rail"><section className="tape-card"><p>ЭКРАН В ЭФИРЕ</p><strong>{room}</strong><small>Нажми любой режим слева — зрительский экран в OBS сменится сам. Его не нужно переключать вручную.</small><Link className="present-link" href={`/screen?room=${room}`} target="_blank">ОТКРЫТЬ ЗРИТЕЛЬСКИЙ ЭКРАН →</Link><p>ПЛАНШЕТЫ ИГРОКОВ</p><input className="share-input" value={shareBase} onChange={e=>setShareBase(e.target.value)} placeholder="https://…trycloudflare.com"/><input className="share-input" value={viviKey} onChange={e=>setViviKey(e.target.value)} placeholder="ключ Виви"/><input className="share-input" value={hinaKey} onChange={e=>setHinaKey(e.target.value)} placeholder="ключ Хиночки"/><a className="player-link" href={playerHref("vivi",viviKey)} target="_blank">ОТКРЫТЬ ПЛАНШЕТ ВИВИ →</a><a className="player-link" href={playerHref("hina",hinaKey)} target="_blank">ССЫЛКА ДЛЯ ХИНОЧКИ →</a><p>ГОЛОСА ЧАТА</p><a className="player-link" href={audienceHref} target="_blank">ОТКРЫТЬ ССЫЛКУ ЧАТА →</a>{chatOptions.length?<div className="vote-count">{chatOptions.map(option=><span key={option}>{option}: <b>{voteTally[option]||0}</b></span>)}</div>:<small>В этом режиме чат просто смотрит и комментирует.</small>}<Button onClick={()=>{sync();log("Экран для зрителей обновлён")}}>ОБНОВИТЬ ЭКРАН</Button><Button onClick={async()=>{await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({room,resetVotes:true})});setVotes([])}}>СБРОСИТЬ ГОЛОСА</Button></section><section className="donation-mini"><p>ДОНАТНАЯ КАССА</p>{lastDonation?<><b>{lastDonation.username} · {lastDonation.amount} ₽</b><strong>{lastDonation.action.title}</strong>{lastDonation.action.toast&&<em>{lastDonation.action.toast}</em>}</>:<small>Ждём первого свидетеля брака.</small>}<Link href="/donations" target="_blank">ОТКРЫТЬ КАССУ →</Link></section><section className="event-log"><p>ПОСЛЕДНИЕ СОБЫТИЯ</p>{history.map((x,i)=><div key={`${x}${i}`}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</section></aside>
  </main>;
}

function Home({status,history,go,random}:{status:string;history:string[];go:(m:Mode)=>void;random:()=>void}){return <section className="panel home"><div className="hero-note"><span>♥</span><p>ЦЕНТРАЛЬНАЯ ИГРА ДЛЯ БОЛТАТЕЛЬНОГО СТРИМА</p><h1>Сначала знакомимся.<br/>Потом <i>случайно</i> женимся.</h1><div><Button kind="primary" onClick={()=>go("roulette")}>КРУТИТЬ РУЛЕТКУ</Button><Button onClick={random}>СЛУЧАЙНОЕ ИСПЫТАНИЕ</Button></div></div><div className="home-grid"><article><b>СТАТУС</b><h2>{status}</h2><p>Все показатели — исключительно повод для рофлов, историй и вмешательства чатерсов.</p></article><article><b>КАК УПРАВЛЯТЬ</b><p>Нажми игру слева — она сразу появится на зрительском экране в OBS. Отдельно ничего переключать не нужно.</p>{[["Выбрать вопрос","questions"],["Открыть бинго","bingo"],["Устроить семейный суд","court"],["Подписать договор","contract"]].map(([t,m])=><button key={t} onClick={()=>go(m as Mode)}>{t}<span>→</span></button>)}</article></div><div className="scribble">★ ЧАТ — ТРЕТИЙ ПОЛНОЦЕННЫЙ ИГРОК ★</div><div className="tiny-history">{history.slice(0,3).map(x=><span key={x}>✦ {x}</span>)}</div></section>}
function Question({question,used,next,answered}:{question:typeof questions[number];used:number;next:(n?:number)=>void;answered:()=>void}){const[n,setN]=useState("");return <section className="panel question"><div className="eyebrow">РЕЖИМ 01 · {question.category}<span>{used}/123 СЫГРАНО</span></div><div className="question-number">{String(question.id).padStart(3,"0")}</div><h1>{question.text}</h1><div className="actions"><Button kind="primary" onClick={answered}>ОТВЕТИЛИ ✓</Button><Button onClick={()=>next()}>ЗАМЕНИТЬ</Button><label>№ <input value={n} onChange={e=>setN(e.target.value)} placeholder="1–123"/><button onClick={()=>{const x=Number(n);if(x>0&&x<124)next(x)}}>ОТКРЫТЬ</button></label></div><p className="host-tip">Не торопитесь: хороший ответ всегда можно превратить в историю.</p></section>}
function Choice({title,names,answers,answerStatus,revealed,reveal,next}:{title:string;names:string[];answers:string[];answerStatus:Record<string,boolean>;revealed:boolean;reveal:()=>void;next:()=>void}){return <section className="panel choice"><div className="eyebrow">{title}</div><h1>{revealed?"Ответы раскрыты. Теперь можно спорить красиво.":"Раунд запущен. Вы отвечаете каждая на своей секретной странице."}</h1><div className="answers">{names.map((name,i)=><article key={name}><p>{name}</p>{revealed?<strong>{answers[i]||"—"}</strong>:<b className={answerStatus[i===0?"vivi":"hina"]?"ready":"waiting"}>{answerStatus[i===0?"vivi":"hina"]?"● ответ отправлен":"○ ждём ответ"}</b>}</article>)}</div><div className="actions"><Button kind="primary" disabled={!answerStatus.vivi||!answerStatus.hina||revealed} onClick={reveal}>{revealed?"ОТВЕТЫ ОТКРЫТЫ":"РАСКРЫТЬ ОДНОВРЕМЕННО"}</Button><Button onClick={next}>СЛЕДУЩЕЕ</Button></div><p className="host-tip">Промпт и варианты смотрите на своих планшетах: Виви и Хиночка не видят ответы друг друга до раскрытия.</p></section>}
function Bingo({bingo,setBingo,has}:{bingo:{text:string;checked:boolean}[];setBingo:(x:{text:string;checked:boolean}[])=>void;has:boolean}){return <section className="panel bingo"><div className="eyebrow">РЕЖИМ 02 · БИНГО ЧАТА</div><h1>{has?"БИНГО!":"Отмечай, когда это случилось"}</h1><div className="bingo-grid">{bingo.map((c,i)=><button className={c.checked?"checked":""} key={`${c.text}${i}`} onClick={()=>setBingo(bingo.map((x,j)=>j===i?{...x,checked:!x.checked}:x))}>{c.checked&&<i>✦</i>}{c.text}</button>)}</div><div className="actions"><Button kind="primary" onClick={()=>setBingo(bingo.map((x,i)=>({text:bingoEvents[(i+Math.floor(Math.random()*15))%bingoEvents.length],checked:false})))}>НОВАЯ КАРТОЧКА</Button><Button onClick={()=>setBingo(bingo.map(x=>({...x,checked:false})))}>СБРОСИТЬ</Button></div></section>}
function Tier({tier,setTier}:{tier:Record<string,string>;setTier:(x:Record<string,string>)=>void}){return <section className="panel tier"><div className="eyebrow">РЕЖИМ 05 · ТИР-ЛИСТ БРАКА</div><h1>Сначала каждый выбирает скрытно. Потом — семейный аудит.</h1><div className="tier-board">{levels.map(l=><article key={l}><b>{l}</b><div>{tierCards.filter(c=>tier[c]===l).map(c=><span key={c}>{c}</span>)}</div></article>)}</div><div className="card-drawer">{tierCards.map(card=><label key={card}>{card}<select value={tier[card]||""} onChange={e=>setTier({...tier,[card]:e.target.value})}><option value="">Выбрать тир</option>{levels.map(l=><option key={l}>{l}</option>)}</select></label>)}</div></section>}
function Court({court,names,seconds,timer,toggle,reset,next,vote}:{court:string;names:string[];seconds:number;timer:boolean;toggle:()=>void;reset:()=>void;next:()=>void;vote:(x:string)=>void}){return <section className="panel court"><div className="eyebrow">РЕЖИМ 06 · СЕМЕЙНЫЙ СУД</div><div className="court-stamp">ДЕЛО №{String(court.length).padStart(2,"0")}</div><h1>{court}</h1><div className="timer"><b>00:{String(seconds).padStart(2,"0")}</b><Button onClick={toggle}>{timer?"ПАУЗА":"СТАРТ ТАЙМЕРА"}</Button><Button onClick={reset}>СБРОС</Button></div><div className="verdicts">{[`${names[0]} права`,`${names[1]} прав`,`Виноваты оба`,`РАЗВОД`].map(x=><button key={x} onClick={()=>vote(x)}>{x}</button>)}</div><Button onClick={next}>ДРУГОЙ КОНФЛИКТ</Button></section>}
function Contract({draft,setDraft,contract,setContract}:{draft:string;setDraft:(x:string)=>void;contract:string[];setContract:(x:string[])=>void}){const copy=()=>navigator.clipboard?.writeText(`БРАЧНЫЙ ДОГОВОР\n${contract.map((x,i)=>`${i+1}. ${x}`).join("\n")}`);const save=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([`БРАЧНЫЙ ДОГОВОР\n${contract.map((x,i)=>`${i+1}. ${x}`).join("\n")}`],{type:"text/plain"}));a.download="brachnyi-dogovor.txt";a.click()};return <section className="panel contract"><div className="eyebrow">РЕЖИМ 07 · БРАЧНЫЙ ДОГОВОР</div><h1>Законы брака, предложенные чатом</h1><div className="contract-maker"><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Чат предлагает: после 23:00 нельзя начинать драму без согласования…"/><Button kind="primary" onClick={()=>{if(draft.trim()){setContract([...contract,draft.trim()]);setDraft("")}}}>ПРИНЯТЬ</Button><Button onClick={()=>setDraft("")}>ОТКЛОНИТЬ</Button></div><ol>{contract.length?contract.map((x,i)=><li key={`${x}${i}`}>{x}<button onClick={()=>setContract(contract.filter((_,j)=>j!==i))}>×</button></li>):<li className="muted">Первый закон ждёт своего чатерса.</li>}</ol><div className="actions"><Button onClick={copy}>СКОПИРОВАТЬ ИТОГ</Button><Button onClick={save}>СКАЧАТЬ .TXT</Button></div></section>}
function Knowledge({names,question,change}:{names:string[];question:string;change:(m:Metric,n:number)=>void}){const[a,setA]=useState(""),[b,setB]=useState(""),[show,setShow]=useState(false);return <section className="panel knowledge"><div className="eyebrow">РЕЖИМ 09 · НАСКОЛЬКО ТЫ МЕНЯ ЗНАЕШЬ?</div><h1>{question}</h1><div className="secret-inputs"><label>Ответ {names[0]}<textarea value={a} onChange={e=>setA(e.target.value)} placeholder="скрытый ответ"/></label><label>Угадывает {names[1]}<textarea value={b} onChange={e=>setB(e.target.value)} placeholder="версия партнёра / чата"/></label></div><div className="actions"><Button kind="primary" onClick={()=>{setShow(true);if(a.trim().toLowerCase()===b.trim().toLowerCase()&&a)change("knowledge",5)}}>СВЕРИТЬ</Button></div>{show&&<p className="result-line">{a.trim().toLowerCase()===b.trim().toLowerCase()&&a?"ПОПАЛИ В ТОЧКУ!":"НУЖЕН ДОПРОС С ПРИСТРАСТИЕМ."}</p>}</section>}
function Dowry({change}:{change:(m:Metric,n:number)=>void}){const qs=["юмор","верность","романтичность","интеллект","терпение","поддержка","деньги","готовка","интересы","животные"];const[v,setV]=useState(Object.fromEntries(qs.map(q=>[q,100])));const total=Object.values(v).reduce((a,b)=>a+b,0);return <section className="panel dowry"><div className="eyebrow">РЕЖИМ 11 · ПРИДАНОЕ</div><h1>Распредели 1000 монет качеств будущего супруга</h1><b className="coin-total">{total} / 1000 💰</b><div className="slider-grid">{qs.map(q=><label key={q}>{q}<input type="range" min="0" max="250" step="10" value={v[q]} onChange={e=>setV({...v,[q]:Number(e.target.value)})}/><output>{v[q]}</output></label>)}</div><Button kind="primary" onClick={()=>change("chemistry",total===1000?5:1)}>ЗАФИКСИРОВАТЬ</Button></section>}
function Life({add}:{add:(x:string)=>void}){const steps=["Где живём","Дом","Питомец","Работа Виви","Транспорт","Сосед","Традиция","Секрет"];const[v,setV]=useState<Record<string,string>>({});return <section className="panel life"><div className="eyebrow">РЕЖИМ 12 · СОВМЕСТНАЯ ЖИЗНЬ</div><h1>Чат проектирует альтернативную семейную реальность</h1><div className="life-grid">{steps.map(s=><label key={s}>{s}<input value={v[s]||""} onChange={e=>setV({...v,[s]:e.target.value})} placeholder="чат решает…"/></label>)}</div><Button kind="primary" onClick={()=>add(Object.entries(v).filter(([,x])=>x).map(([k,x])=>`${k}: ${x}`).join(" · "))}>СОЗДАТЬ НАШУ ЖИЗНЬ</Button></section>}
function Roulette({value,spin}:{value:string;spin:()=>void}){return <section className="panel roulette"><div className="eyebrow">РЕЖИМ 13 · СВАДЕБНАЯ РУЛЕТКА</div><div className="roulette-wheel"><b>{value}</b></div><Button kind="primary" onClick={spin}>КРУТИТЬ</Button><p>Алкогольный сектор — всегда добровольный; его можно заменить водой или отключить в <code>lib/game-data.ts</code>.</p></section>}
function Final({names,status,metrics}:{names:string[];status:string;metrics:Record<Metric,number>}){const title="Семейный DLC успешно установлен.";return <section className="panel final"><p>ФИНАЛЬНЫЙ ЭКЗАМЕН</p><h1>{title}</h1><div className="final-seal">{status}</div><h2>{names.join(" × ")}</h2><div>{(Object.keys(metricLabels) as Metric[]).map(m=><span key={m}>{metricLabels[m]} <b>{metrics[m]}</b></span>)}</div><Button kind="primary" onClick={()=>window.print()}>РАСПЕЧАТАТЬ РЕЗУЛЬТАТ</Button></section>}
